/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {
    'landing-page': LandingPage;
  };
  globalsSelect: {
    'landing-page': LandingPageSelect<false> | LandingPageSelect<true>;
  };
  locale: 'en' | 'ar';
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page".
 */
export interface LandingPage {
  id: number;
  nav: {
    logoText: string;
    logoSubtext: string;
    features: string;
    howItWorks: string;
    technology: string;
    team: string;
    faq: string;
    viewDemo: string;
    login: string;
    language: string;
  };
  hero: {
    headline: string;
    headlineHighlight: string;
    subheadline: string;
    downloadApp: string;
    watchDemo: string;
    activeUsers: string;
    activeUsersText: string;
    heroImage?: (number | null) | Media;
  };
  features: {
    badge: string;
    title: string;
    subtitle: string;
    items: {
      icon: string;
      title: string;
      description: string;
      linkText: string;
      id?: string | null;
    }[];
  };
  howItWorks: {
    badge: string;
    title: string;
    subtitle: string;
    steps: {
      number: string;
      title: string;
      description: string;
      id?: string | null;
    }[];
    whyChooseBadge: string;
    whyChooseTitle: string;
    whyChooseSubtitle: string;
    whyChooseItems: {
      icon: string;
      title: string;
      description: string;
      id?: string | null;
    }[];
    whyChooseImage?: (number | null) | Media;
    statBadge1Value: string;
    statBadge1Label: string;
    statBadge2Value: string;
    statBadge2Label: string;
  };
  techStack: {
    badge: string;
    title: string;
    subtitle: string;
    items: {
      icon: string;
      title: string;
      description: string;
      color: string;
      id?: string | null;
    }[];
    bottomItems: {
      icon: string;
      title: string;
      description: string;
      id?: string | null;
    }[];
  };
  team: {
    badge: string;
    title: string;
    subtitle: string;
    members: {
      icon: string;
      name: string;
      role: string;
      description: string;
      id?: string | null;
    }[];
  };
  faq: {
    badge: string;
    title: string;
    subtitle: string;
    questions: {
      question: string;
      answer: string;
      id?: string | null;
    }[];
  };
  footer: {
    logoText: string;
    logoSubtext: string;
    description: string;
    quickLinksTitle: string;
    quickLinks: {
      label: string;
      url: string;
      id?: string | null;
    }[];
    resourcesTitle: string;
    resources: {
      label: string;
      url: string;
      id?: string | null;
    }[];
    copyright: string;
  };
  cta: {
    title: string;
    subtitle: string;
    downloadIos: string;
    downloadAndroid: string;
    feature1: string;
    feature2: string;
    feature3: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing-page_select".
 */
export interface LandingPageSelect<T extends boolean = true> {
  nav?:
    | T
    | {
        logoText?: T;
        logoSubtext?: T;
        features?: T;
        howItWorks?: T;
        technology?: T;
        team?: T;
        faq?: T;
        viewDemo?: T;
        login?: T;
        language?: T;
      };
  hero?:
    | T
    | {
        headline?: T;
        headlineHighlight?: T;
        subheadline?: T;
        downloadApp?: T;
        watchDemo?: T;
        activeUsers?: T;
        activeUsersText?: T;
        heroImage?: T;
      };
  features?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              linkText?: T;
              id?: T;
            };
      };
  howItWorks?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        steps?:
          | T
          | {
              number?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        whyChooseBadge?: T;
        whyChooseTitle?: T;
        whyChooseSubtitle?: T;
        whyChooseItems?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        whyChooseImage?: T;
        statBadge1Value?: T;
        statBadge1Label?: T;
        statBadge2Value?: T;
        statBadge2Label?: T;
      };
  techStack?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              color?: T;
              id?: T;
            };
        bottomItems?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        members?:
          | T
          | {
              icon?: T;
              name?: T;
              role?: T;
              description?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        questions?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        logoText?: T;
        logoSubtext?: T;
        description?: T;
        quickLinksTitle?: T;
        quickLinks?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        resourcesTitle?: T;
        resources?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        copyright?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        subtitle?: T;
        downloadIos?: T;
        downloadAndroid?: T;
        feature1?: T;
        feature2?: T;
        feature3?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
